// client-react/src/components/Pokemon/Pokemon.jsx
import React, { Component } from "react";
import "./Pokemon.css";
import { Link } from "react-router-dom";


export default class Pokemon extends Component {
    render() {
        const { pokemon } = this.props;
        const { name, number } = pokemon;
        return (
            <Link to={`/pokemons/${number}`}>
                <figure>
                    <img className={"pokemon-img"}
                         src={`https://raw.githubusercontent.com/epam-js-may-2018/homework-7-js/master/pokemons/${number}.png`}/>
                    <figcaption className={"pokemon-name"}>{name.charAt(0).toUpperCase() + name.slice(1)}</figcaption>
                </figure>
            </Link>
        );
    }
}

// client-angular/src/app/modules/pokemons/components/pokemon/pokemon.component.ts
import {Component, Input, OnInit} from '@angular/core';
import { Pokemon } from '../../../../domain/Pokemon';

@Component({
  selector: 'app-pokemon',
  templateUrl: './pokemon.component.html',
  styleUrls: ['./pokemon.component.scss']
})
export class PokemonComponent implements OnInit {

  @Input() pokemon: Pokemon;
  srcImage: string;
  linkPokemon: string;
  constructor() {
  }

  ngOnInit() {
    this.srcImage = `https://raw.githubusercontent.com/epam-js-may-2018/homework-7-js/master/pokemons/${this.pokemon.id}.png`;
    this.linkPokemon = `/pokemons/${this.pokemon.id}`
  }

}

<a routerLink={{linkPokemon}}>
  <figure class="pokemon">
    <img class="pokemon__img" src={{srcImage}} />
    <figcaption class = "pokemon__name">{{pokemon.name | titlecase}}</figcaption>
  </figure>
</a>
