// src/components/Pokemon/Pokemon.jsx
import React, { Component } from "react";
import "./Pokemon.css";
import { Link } from "react-router-dom";


export default class Pokemon extends Component {
    render() {
        let { pokemon } = this.props;
        let { name, id } = pokemon;
        return (
            <Link to={`/pokemons/${id}`}>
                <figure>
                    <img className={"pokemon-img"}
                         src={`https://raw.githubusercontent.com/epam-js-may-2018/homework-7-js/master/pokemons/${pokemon.id}.png`}/>
                    <figcaption className={"pokemon-name"}>{name.charAt(0).toUpperCase() + name.slice(1)}</figcaption>
                </figure>
            </Link>
        );
    }
}

// client-angular/src/app/pokemons/pokemon/pokemon.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-pokemon',
  templateUrl: './pokemon.component.html',
  styleUrls: ['./pokemon.component.css']
})
export class PokemonComponent implements OnInit {

  name = "pokemon";
  id = 1;
  src = `https://raw.githubusercontent.com/epam-js-may-2018/homework-7-js/master/pokemons/${this.id}.png`;
  constructor() {
  }

  ngOnInit() {
  }

}

<figure>
  <img class = "pokemon-img"
       src = {{src}}/>
  <figcaption class = "pokemon-name">{{name.charAt(0).toUpperCase() + name.slice(1)}}</figcaption>
</figure>
